document.write("<p>");
document.write(asignatura.curso);
document.write("</p>");
document.write("<p>");
document.write(asignatura.alumno);
document.write("</p>");
document.write("<p>");
document.write(asignatura.email);
document.write("</p>");